"""Ranged schedule answers ("what does my month look like") — Phase 2D.3, defect R1.

Reads the real calendar for an arbitrary [start, end) window (paginated, so a month never truncates)
and renders a grouped-by-day summary. Like the week path, the answer is BUILT from provider events —
never generated by the model — so it can't invent a schedule. A disconnected calendar is reported
honestly, not papered over.
"""
from __future__ import annotations

from datetime import date
from zoneinfo import ZoneInfo

from app.config import get_settings
from app.integrations.google import calendar
from app.query.answer import ProviderFact, StructuredAnswer
from app.query.ranges import TimeRange
from app.security.crypto import EncryptionUnavailableError
from app.sources import registry
from app.telemetry import get_logger

log = get_logger(__name__)

_NOT_CONNECTED = (
    "I'm not connected to your Google Calendar yet. Ask me to connect (or hit "
    "/integrations/google/connect) to grant read-only access."
)
_NO_KEY = "I can't read your calendar yet — the encryption key isn't configured on the server."
_ERROR = "Sorry — I couldn't reach your calendar just now. Try again in a moment."


def _tz() -> ZoneInfo:
    try:
        return ZoneInfo(get_settings().tz)
    except Exception:  # noqa: BLE001
        return ZoneInfo("UTC")


def _event_line(event: calendar.CalendarEvent, tz: ZoneInfo) -> str:
    if event.all_day:
        return f"• {event.summary} (all day)"
    when = event.start.astimezone(tz).strftime("%-I:%M %p").lstrip("0")
    where = f" @ {event.location}" if event.location else ""
    return f"• {when} — {event.summary}{where}"


async def build_answer(
    text: str, time_range: TimeRange, account: str = "default"
) -> StructuredAnswer:
    """Assemble the StructuredAnswer for a ranged schedule query (evidence before prose)."""
    report = await registry.calendar_report(account)
    answer = StructuredAnswer(
        question=text,
        intent="schedule_range",
        time_range=time_range.as_dict(),
        source_status=[report],
        empty_state=f"You have nothing on your calendar {time_range.label}. 🎉",
    )
    if not report.connected:
        answer.headline = _NOT_CONNECTED
        return answer

    events = await calendar.list_events_range(time_range.start, time_range.end, account=account)
    tz = _tz()
    for event in sorted(events, key=lambda e: e.start):
        answer.provider_facts.append(
            ProviderFact(
                source="calendar",
                provider_object_id=event.event_id,
                text=_event_line(event, tz),
                when=event.start,
            )
        )
    return answer


def _render(answer: StructuredAnswer, time_range: TimeRange) -> str:
    if not answer.provider_facts:
        return answer.headline or answer.empty_state or _ERROR
    tz = _tz()
    by_day: dict[date, list[ProviderFact]] = {}
    for fact in answer.provider_facts:
        day = fact.when.astimezone(tz).date() if fact.when else time_range.start.date()
        by_day.setdefault(day, []).append(fact)

    lines = [f"Here's your {time_range.label}:"]
    for day in sorted(by_day):
        lines.append(f"\n{day.strftime('%A %b %-d')}:")
        for fact in by_day[day]:
            lines.append(f"  {fact.text}")
    return "\n".join(lines)


async def handle(text: str, time_range: TimeRange, account: str = "default") -> str:
    """Answer a ranged schedule query from the calendar. Never raises."""
    try:
        answer = await build_answer(text, time_range, account)
    except calendar.NotConnectedError:
        return _NOT_CONNECTED
    except EncryptionUnavailableError:
        return _NO_KEY
    except Exception as exc:  # noqa: BLE001 — friendly to user, detail to logs.
        log.error("schedule_range_failed", error=str(exc), error_type=type(exc).__name__)
        return _ERROR
    return _render(answer, time_range)
