"""Deterministic dashboard mode selection (Phase 2F.0) — pure, no LLM.

The mode drives layout emphasis. It is chosen by explicit rules over objective signals (time to next
event, deadline urgency, approval expiry, source health, focus) — never generated by a model, so the
layout is always explainable and validatable. Priority order is fixed: the most urgent situation wins.
"""
from __future__ import annotations

from dataclasses import dataclass

from app.dashboard.contracts import DashboardMode

PRE_EVENT_WINDOW_MIN = 60
TRAVEL_WINDOW_MIN = 180
DEEP_WORK_MIN_CLEAR_MIN = 120
APPROVAL_CRISIS_MIN = 10


@dataclass(frozen=True)
class ModeSignals:
    minutes_to_next_event: float | None = None
    next_event_is_travel: bool = False
    top_deadline_urgency: str | None = None       # high | normal | low
    approvals_pending: int = 0
    soonest_approval_expiry_minutes: float | None = None
    calendar_connected: bool = True
    gmail_connected: bool = True
    has_conflict: bool = False
    high_priority_waiting: int = 0
    focus: str | None = None


def select_mode(s: ModeSignals) -> DashboardMode:
    """Choose the dashboard mode deterministically from objective signals."""
    imminent_approval = (
        s.approvals_pending > 0
        and s.soonest_approval_expiry_minutes is not None
        and s.soonest_approval_expiry_minutes <= APPROVAL_CRISIS_MIN
    )
    if imminent_approval or (not s.calendar_connected and not s.gmail_connected):
        return DashboardMode.CRISIS

    within = s.minutes_to_next_event is not None and s.minutes_to_next_event >= 0
    if within and s.next_event_is_travel and s.minutes_to_next_event <= TRAVEL_WINDOW_MIN:
        return DashboardMode.TRAVEL
    if within and s.minutes_to_next_event <= PRE_EVENT_WINDOW_MIN:
        return DashboardMode.PRE_EVENT
    if s.top_deadline_urgency == "high":
        return DashboardMode.DEADLINE

    clear_ahead = s.minutes_to_next_event is None or s.minutes_to_next_event > DEEP_WORK_MIN_CLEAR_MIN
    if s.focus and clear_ahead:
        return DashboardMode.DEEP_WORK
    return DashboardMode.IDLE


# Travel keywords (title or location) used upstream to set next_event_is_travel.
TRAVEL_KEYWORDS = (
    "flight", "airport", "terminal", "gate ", "boarding", "train", "station", "amtrak",
    "depart", "arrival", "uber", "lyft", "drive to", "commute", "bus to", "ferry",
)


def looks_like_travel(*texts: str | None) -> bool:
    blob = " ".join(t.lower() for t in texts if t)
    return any(k in blob for k in TRAVEL_KEYWORDS)
